language: ruby

rvm:
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.15
  - jruby-1.7.27

build:
  pre_ci:
    - echo 'true'
  pre_ci_boot:
    image_name: drydock/u14ruball
    image_tag: master
    pull: true
    options: '--privileged=true --net=bridge -e FOO=true -e BOO=false'
    
  ci:
    - printenv
    - java -version    
    - nvm ls
    - ruby -e "puts 'Hello, world!'"
    
jobs:
  - name: ruby_u14ruball_test
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
          name: version_jruby-9.1.15
          runtime:
            options:
              imageName: "drydock/u14ruball"
              imageTag: "master"
          script:
            - source /usr/local/rvm/scripts/rvm
            - rvm use jruby-9.1.15
            - ruby -e "puts 'Hello, world!'"
      - TASK:
          name: version_jruby-1.7.27
          runtime:
            options:
              imageName: "drydock/u14ruball"
              imageTag: "master"
          script:
            - source /usr/local/rvm/scripts/rvm
            - rvm use jruby-1.7.27
            - ruby -e "puts 'Hello, world!'"   
      - TASK:
          name: version_2.2.8
          runtime:
            options:
              imageName: "drydock/u14ruball"
              imageTag: "master"
          script:
            - source /usr/local/rvm/scripts/rvm
            - rvm use 2.2.8
            - ruby -e "puts 'Hello, world!'"     
      - TASK:
          name: version_2.3.6
          runtime:
            options:
              imageName: "drydock/u14ruball"
              imageTag: "master"
          script:
            - source /usr/local/rvm/scripts/rvm
            - rvm use 2.3.6
            - ruby -e "puts 'Hello, world!'"     
      - TASK:
          name: version_2.4.3
          runtime:
            options:
              imageName: "drydock/u14ruball"
              imageTag: "master"
          script:
            - source /usr/local/rvm/scripts/rvm
            - rvm use 2.4.3
            - ruby -e "puts 'Hello, world!'"     
      - TASK:
          name: version_2.5.0
          runtime:
            options:
              imageName: "drydock/u14ruball"
              imageTag: "master"
          script:
            - source /usr/local/rvm/scripts/rvm
            - rvm use 2.5.0
            - ruby -e "puts 'Hello, world!'"                 
